Resources:
  POSTGRESDB:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: techwondoedb
      Engine: postgres
      MasterUsername: anand
      MasterUserPassword: anandspassword
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro

  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    DependsOn:
      - TriggerLambdaPermission
    Properties:
      BucketName: techwondoe-data
      AccessControl: Private
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !GetAtt LAMBDAFN.Arn

  LAMBDAFN:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: codebucket01
        S3Key: lambdacode.zip 

      Handler: index.handler
      Role: arn:aws:iam::073097280998:role/role_for_lambda_fn
      Runtime: python3.8

  TriggerLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !Ref LAMBDAFN
      Principal: s3.amazonaws.com
      SourceArn: !Sub "arn:aws:s3:::techwondoe-data"
      SourceAccount: !Ref AWS::AccountId

Outputs:
  BucketName:
    Value: !Ref S3Bucket
    Description: Name of the bucket

  DBEndpoint:
    Value: !GetAtt POSTGRESDB.Endpoint.Address
    Description: The endpoint of the RDS database
